### ISSUE TITLE
Not enough relays received the message on site setting save

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-site-cli#3]
I created nostr keypair using Damus, and it picked up some local relays for my account. 
Only 5/7 of them are online:

![IMAGE 2024-10-16 15:57:25](https://github.com/user-attachments/assets/764706ba-ddbe-4e38-9486-4b09cf514d35)

I was able to create and publish a site, but when i edit settings/theme i recieve an error not enough relays recieved a message: 

<details><summary>None of the relays saved the message on site setting edit</summary>
<img width="1912" alt="Screenshot 2024-10-16 at 16 00 43" src="https://github.com/user-attachments/assets/91b777e0-8fec-4b29-94fb-ffcd0fb60ca2">
<img width="1912" alt="Screenshot 2024-10-16 at 16 00 38" src="https://github.com/user-attachments/assets/f5036878-5dfc-4853-b309-5aee8c6126e1">
<img width="1912" alt="Screenshot 2024-10-16 at 16 00 28" src="https://github.com/user-attachments/assets/60d6d020-3f0c-4cef-90c5-c47c09b23823">
<img width="1912" alt="Screenshot 2024-10-16 at 16 00 26" src="https://github.com/user-attachments/assets/bea807e0-d5be-44cb-b726-c45d7b594283">

</details>

1. Nos.lol and damus.io relays are missing even when they're configured for my profile through damus app (by default)
2. Is it possible to use a list of "default" relays user will be connected to make sure site settings are saved somewhere on relay? 

Maybe we should rethink solution of site-configuration storage to make UX more flawless? 
Save settings on our side if relays are not available?

**Comment by nostrband** [comment]
There should at least be relay.npubpro.com where all sites are saved. Please check again - is there this relay and is your site edit getting written there?

**Comment by leafes** [comment]
now its get written into relay.npubpro.com
![Image](https://github.com/user-attachments/assets/3473353a-cfbe-4c5b-9cd1-026fbf5566e4)

i think unability to save was related to this issue https://github.com/nostrband/nostr-site-manager/pull/101 
one of availiable relay wasn't able to write the message due to incorrect "created_at" field

**Comment by leafes** [comment]
i suggest to consider this issue as solved
